### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DemonXslayer47** [vakhil-98/Bworks#1]
Can you be more specific about the Architecture in your document?
more information about how you want it to work.
what do you mean by business layer can you be more specific?
How is the database accessed?

**Comment by vakhil-98** [comment]
Yea, I'd be more specific once I get few more details requested from the client. So by business layer I mean it's the layer that maps the data received from the front end to the particular attributes in a table.
Database would be accessed in the business layer.
